# Generated by Django 3.0.7 on 2020-07-30 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='Day the test was given')),
                ('results_date', models.DateField(blank=True, null=True, verbose_name='Day the results were recieved')),
                ('location', models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Off-site', 'Off-site')], default='', max_length=10, verbose_name='Location of Test Taken(on - site / off - site)')),
                ('test_status', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='', max_length=8, verbose_name='Status(Positive/Negative)')),
            ],
            options={
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Team Member Name')),
                ('phone_number', models.CharField(blank=True, default='', max_length=10, verbose_name='Phone number')),
                ('company', models.CharField(blank=True, choices=[('MBUSI', 'MBUSI'), ('Onin', 'Onin'), ('NAOS', 'NAOS'), ('Contractor', 'Contractor')], default='', max_length=24, verbose_name='Company (MBUSI, NAOS, etc.)')),
                ('badge_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Employee ID Badge Number')),
                ('shop', models.CharField(blank=True, default='', max_length=24, verbose_name='Plant (Admin, A1, etc.)')),
                ('line', models.CharField(blank=True, default='', max_length=24, verbose_name='Work Area or line (Trim 2, HR, etc.)')),
                ('shift', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Shift (A, B, C)')),
                ('test', models.ManyToManyField(related_name='Test_Results', to='tracking.Test')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_date', models.DateField(blank=True, null=True, verbose_name='The date the case opened')),
                ('concern', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Exposure', 'Exposure'), ('Symptom', 'Symptom'), ('Quarantine', 'Quarantine')], default='', max_length=11, verbose_name='Concern(Positive, Exposure, Symptom, Quarantine)')),
                ('discription', models.CharField(blank=True, default='', max_length=1000, verbose_name='Discription')),
                ('last_day_worked', models.DateField(blank=True, null=True, verbose_name='Last Day Worked')),
                ('case_closed', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='', max_length=11, verbose_name='Case(Open, Closed)')),
                ('close_contact', models.ManyToManyField(blank=True, default='', null=True, related_name='Close_Contacts', to='tracking.Person')),
                ('manager', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='tracking.Person')),
                ('team_member', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='Team_Member', to='tracking.Person')),
            ],
            options={
                'ordering': ['-encounter_date'],
            },
        ),
    ]
