# Generated by Django 3.0.7 on 2020-07-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='Test_Results', to='tracking.Test'),
        ),
    ]
