# Generated by Django 3.0.7 on 2020-07-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200730_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='close_contact',
            field=models.ManyToManyField(default='', null=True, related_name='Close_Contacts', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='manager',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='team_member',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_Member', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, choices=[('MBUSI', 'MBUSI'), ('Onin', 'Onin'), ('NAOS', 'NAOS'), ('Contractor', 'Contractor')], default='MBUSI', max_length=24, verbose_name='Company (MBUSI, NAOS, etc.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='line',
            field=models.CharField(blank=True, default='A', max_length=24, verbose_name='Work Area or line (Trim 2, HR, etc.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='test',
            field=models.ManyToManyField(null=True, related_name='Test_Results', to='tracking.Test'),
        ),
    ]
