# Generated by Django 3.0.7 on 2020-07-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200731_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='close_contact',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='Close_Contacts', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='line',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Work Area or line (Trim 2, HR, etc.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shift',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1, verbose_name='Shift (A, B, C)'),
        ),
    ]
