# Generated by Django 3.0.7 on 2020-07-31 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20200731_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='team_member',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_Member', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='test',
            field=models.ManyToManyField(blank=True, null=True, related_name='Test_Results', to='tracking.Test'),
        ),
    ]
