# Generated by Django 3.0.7 on 2020-07-31 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20200731_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='close_contact',
            field=models.ManyToManyField(blank=True, null=True, related_name='Close_Contacts', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='team_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_Member', to='tracking.Person'),
        ),
    ]
