# Generated by Django 3.0.7 on 2020-08-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20200731_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['-results_date']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='test',
        ),
        migrations.AddField(
            model_name='test',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Test_Case', to='tracking.Case'),
        ),
        migrations.AlterField(
            model_name='case',
            name='close_contact',
            field=models.ManyToManyField(blank=True, related_name='Close_Contacts', to='tracking.Person'),
        ),
        migrations.AlterField(
            model_name='case',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_Member', to='tracking.Person'),
        ),
    ]
