# Generated by Django 3.0.7 on 2020-08-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20200803_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='encounter_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date the Case Opened'),
        ),
        migrations.AlterField(
            model_name='test',
            name='location',
            field=models.CharField(blank=True, choices=[('On-site', 'On-site'), ('Off-site', 'Off-site')], default='', max_length=10, verbose_name='Location of Test Taken(on-site / off-site)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='results_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Results Recieved'),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Test Was Given'),
        ),
    ]
