# Generated by Django 3.0.7 on 2020-08-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20200804_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager', to='tracking.Person'),
        ),
    ]
