# Generated by Django 3.0.3 on 2021-01-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20200807_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.CharField(blank=True, choices=[('Internal', 'Internal'), ('External', 'External'), ('Contractor', 'Contractor'), ('Other', 'Other')], default='Internal', max_length=24, verbose_name='Company (Main etc.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='line',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Work Area or line (HR, etc.)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='shop',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='Plant (Admin, etc.)'),
        ),
    ]
